### PR TITLE
first addition for directgma

### PR DESCRIPTION
**Pull request by evoliptic**
test

### CODE REVIEW

**Comment by evoliptic** [comment]
ok, this shoud be ok in core from the gpu part for directgma. 
However, there is still some things i'm not sure : see how to say we want that in resources for example.
ciao!

**Comment by matze** [comment]
We also need a way to detect that we compile against an AMD SDK, otherwise Travis CI will always complain. I'll try to figure out something.

**Comment by matze** [comment]
Can you apply [this](https://gist.github.com/matze/4ac104513064aa1928ba) patch using `git am 0001 ...`? This checks for the AMD-only `mem_flag` and compiles your stuff only if possible. It also cleans up some of the mess …

**Comment by evoliptic** [comment]
patch applied and some modif done in ufo-resource

**Comment by matze** [comment]
[This](https://gist.github.com/matze/376a7695ed3e8a0cb6af) is another patch that properly defines `HAVE_AMD`. Could you apply that (and this time keep authorship as is)?

**Pull request closed without merging**
