### PR TITLE
Specify channel order based on OpenCL capabilities

### PR DESCRIPTION
**Pull request by tfarago**
Now we will finally be able to dynamically handle various channel orders supported for `CL_FLOAT` data type. I have implemented it in the buffer in a very dynamic way which will create a tiny overhead but the code is _way_ shorter and we don't need to mess with the python ufo.numpy.

### CODE REVIEW

**Comment by matze** [comment]
Looks good, maybe make the `g_warning` a `g_error` however unlikely it is to occur in reality. Do you have performance numbers already? And why the heck have never noticed that low-hanging fruit?

**Comment by tfarago** [comment]
Right, it's changed. However, there is no performance bump because on HW side (at least on NVIDIA) nothing changes. To populate all channels with one value takes no time, or they even fake it and don't do it actually, who knows... I got 10 s for CL_INTENSITY and CL_R and 100 sinograms of size 2024x3000.

**Comment by tfarago** [comment]
So this is a PR about compatibility, not performance optimization.

**Comment by tfarago** [comment]
Related also to #86

**Pull request merged**
