### PR TITLE
Fixed ufo-arch-graph getting passed wrong data type for param remotes

### PR DESCRIPTION
**Pull request by TimoDritschler**
I found that the ```UfoArchGraph``` expects a ```GList``` for the _remotes_ argument, but handles it like a _boxed type_ ```GValueArray```, so I have fixed the function declaration and definitions.
This does not change the GIR binding, but it changes the C interface. What is your feeling about this? I guess, since the clustering was broken anyways, I don' think there will be too many people being affected by this API change.

Also, just to make sure: This is a pull request into the ```fix-cluster``` feature branch. Not into the mainline.

### CODE REVIEW

**Comment by matze** [comment]
> What is your feeling about this?

I think that's okay.

> Also, just to make sure: This is a pull request into the fix-cluster feature branch. Not into the mainline.

Perhaps, wait a day or two with major changes until I complete the changes in that branch and it's merged in mainline.

**Comment by TimoDritschler** [comment]
Okay, no problem

**Comment by matze** [comment]
You can rebase this branch against master, check and force-push.

**Comment by TimoDritschler** [comment]
Apparently, I can't change the branches of the pull request once it is created. Do you want me to open a new one or just push my enormous 3-line diff onto master?

**Comment by matze** [comment]
Push to master.

**Comment by TimoDritschler** [comment]
Okay, thanks

**Pull request closed without merging**
